name: "Stage Deployment" 
    
on:
  push:
    branches:
      - main
    
jobs:
  deploy_stage:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
          
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: "1.6"
          
      - name: Deploy Info
        run: echo "Deployment workflow ready"
